apiVersion: v1
kind: ConfigMap
metadata:
  name: pu2pay-config
data:
  POSTGRES_DB: pu2pay_v1
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"